// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHYTJ0E6MbkXH-jMAkYT3ZLpp4wHav_2Y',
    appId: '1:26224492150:web:2f8738468a24c321c82957',
    messagingSenderId: '26224492150',
    projectId: 'spotifynew010101',
    authDomain: 'spotifynew010101.firebaseapp.com',
    storageBucket: 'spotifynew010101.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE3kRrJ2rGk0e5LS2GkPva0F7JoPL-mko',
    appId: '1:26224492150:android:d4861f9b40c76290c82957',
    messagingSenderId: '26224492150',
    projectId: 'spotifynew010101',
    storageBucket: 'spotifynew010101.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa_xwbtgPhT62dbMESo6Sf6INuYcPMZkc',
    appId: '1:26224492150:ios:94418e23bbf2ca28c82957',
    messagingSenderId: '26224492150',
    projectId: 'spotifynew010101',
    storageBucket: 'spotifynew010101.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa_xwbtgPhT62dbMESo6Sf6INuYcPMZkc',
    appId: '1:26224492150:ios:94418e23bbf2ca28c82957',
    messagingSenderId: '26224492150',
    projectId: 'spotifynew010101',
    storageBucket: 'spotifynew010101.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHYTJ0E6MbkXH-jMAkYT3ZLpp4wHav_2Y',
    appId: '1:26224492150:web:a6ff1063834c4ddac82957',
    messagingSenderId: '26224492150',
    projectId: 'spotifynew010101',
    authDomain: 'spotifynew010101.firebaseapp.com',
    storageBucket: 'spotifynew010101.firebasestorage.app',
  );
}
